### ISSUE TITLE
rubocop offenses

### ISSUE THREAD

**Issue by iankronquist** [osuosl-cookbooks/python-webapp#1]
Fix them now before we get a zillion.

**Comment by justinnoah** [comment]
Git hook to run rubocop before merges into the main branch?

**Comment by tschuy** [comment]
@brutal-chaos can you make git hooks shared between users? I think those are per-clone.

Will set up travis, however.

**Comment by justinnoah** [comment]
true, i meant github side. though, with travis ci indicators, the same is loosely in effect.
