### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by pop** [osuosl-cookbooks/python-webapp#11]
An ongoing issue for testing.

I will do the initial infrastructure which will look similar to https://github.com/chef-cookbooks/yum/blob/master/TESTING.md adjusted to fit our needs.

**Comment by iankronquist** [comment]
Updated title to differentiate it from @tschuy's issue #5 which is for integration testing.

**Comment by iankronquist** [comment]
How is this going? It would be nice, but not necessary, for this to land before #6 does.

**Comment by tschuy** [comment]
Fixed by #16
