### ISSUE TITLE
Usage docs

### ISSUE THREAD

**Issue by tschuy** [osuosl-cookbooks/python-webapp#19]
We currently have lots of docs on how to run the tests. We have none on how to **use** the LWRP. 

This _should wait_ until the gunicorn branch I'm working on gets merged into common_recipe, and common_recipe gets merged into master.

@MaraJade @iankronquist

**Comment by iankronquist** [comment]
Waiting? Who waits to get things done? I'll put this on my plate for next week.

**Comment by tschuy** [comment]
@iankronquist++

**Comment by pop** [comment]
I was about to use this to re-write part of the PGD cookbook and realized there's no docs. I'm just gonna go ahead and get some usage docs written.
Beyond usage docs we should compile a list of other docs that need to be written.

**Comment by mathuin** [comment]
Battle of the dueling pull requests!  Two developers enter, one commit leaves...

Seriously, having developer documentation and operations documentation will make this much easier for us in the future.

**Comment by iankronquist** [comment]
@ElijahCaine We have testing docs, and anyone who is going to be working on this will have some familiarity with Chef, so I'd say usage docs are all we need.

**Comment by tschuy** [comment]
@ElijahCaine can this be closed? This is fixed by #23 correct?
