### ISSUE TITLE
Support not using virtualenv

### ISSUE THREAD

**Issue by tschuy** [osuosl-cookbooks/python-webapp#25]
Add a bool for disabling virtualenv. This would essentially involve using a pythonbin_path internally, rather than the virtualenv_path. If we're using virtualenvs, pythonbin_path would be either virtualenv_path, if set, or the default generated path from before. If we're not, it could just be set to /usr/.

All python calls internally should be using #{pythonbin_path}/bin/python (or gunicorn, where applicable). 

There might need to be an additional if for python_pip.

**Comment by armiller** [comment]
@tschuy was this resolved in #14?

**Comment by tschuy** [comment]
I think we don't actually need to support this, `virtualenv` is lightweight enough as is and provides some pros without really providing many cons.
