### ISSUE TITLE
Custom wsgi location

### ISSUE THREAD

**Issue by tschuy** [osuosl-cookbooks/python-webapp#30]
wsgi files shouldn't have to live in `project/wsgi.py`, since it's **python** webapp, not **django** webapp.

**Comment by iankronquist** [comment]
@tschuy can this be closed?
https://github.com/osuosl-cookbooks/python-webapp/commit/27c8019f0869dc312b650681bcd85660acb1e50b

**Comment by tschuy** [comment]
Yep :)
