### ISSUE TITLE
Gunicorn does not restart on chef run

### ISSUE THREAD

**Issue by matthewrsj** [osuosl-cookbooks/python-webapp#32]
This caused an issue with gunicorn using an old version of Formsender until I ran `supervisorctl restart formsender`

**Comment by tschuy** [comment]
This should theoretically be as simple as `notifies :restart, "supervisor_service[webapp]"`

**Comment by jordane** [comment]
Any comment that begins with

> This should theoretically be as simple as

is required, [by law](http://words.steveklabnik.com/theory-and-practice), to end with

> But in practice it as complicated as
