### ISSUE TITLE
Integration Testing setup

### ISSUE THREAD

**Issue by tschuy** [osuosl-cookbooks/python-webapp#4]
This means a .kitchen.(cloud).yml file, Berksfile, test cookbook, etc set up to run tests.

**Comment by justinnoah** [comment]
@tschuy should this be closed now?

if #5 was to be the PR for this, add 'fixes #4' (no quotes) in the details and it'll autoclose when merged.

**Comment by tschuy** [comment]
@justinnoah yes, it was.
