### ISSUE TITLE
Common cookbook resource

### ISSUE THREAD

**Issue by tschuy** [osuosl-cookbooks/python-webapp#6]
@iankronquist is working on the common lwrp. See https://github.com/osuosl-cookbooks/python-webapp-cookbook/tree/common_recipe

Should we have a :name_badge: :name field? 

Also, should this provide the ability to install a list of packages.

**Comment by iankronquist** [comment]
I don't know what a "flaming no-entry sign" :name field is.
In all seriousness, what would a `:name` field do?
Also, I believe it should install packages and I added an attribute for that.

**Comment by iankronquist** [comment]
Blocked on PR #5 so I can write tests for my changes.
Comments on the latest version would be appreciated.

**Comment by tschuy** [comment]
How much do we want to cover in unit testing, and how much in integration testing? you already have a pretty good maximal case, see the comment on #14 regarding the test case already written. We could write a second integration test that tests all of the default cases.
