### ISSUE TITLE
Django resource

### ISSUE THREAD

**Issue by tschuy** [osuosl-cookbooks/python-webapp#7]
What should the Django resource handle?
- python paclages
- database settings? (or do we just pass these in the main settings hash?)
- debug as a special setting? (applcation_python has this but I don't feel a need for it)
- subdirectory -- might use this so that we can deploy from the python-test-apps repo without making a billion repos. Otherwise, we can use a branch.
- collectstatic

**Comment by iankronquist** [comment]
I think:
1. Python packages should be handled by the common recipe.
2. Database settings should be passed to the main settings hash.
3. We don't need this.
4. We don't need this. It is unusual. If we need it later we can add it.
5. This should not happen by default - not all projects or configurations need it. A must-have though.

**Comment by iankronquist** [comment]
A preliminary version of my vision for the django resource can be found on the `django_resource` branch.

**Comment by justinnoah** [comment]
I 2nd @iankronquist, though for 5, while collectstatic should not be default, the option should be provided.

**Comment by tschuy** [comment]
Essentially this leaves the Django resource as collectstatic? Which isn't even on by default?

**Comment by tschuy** [comment]
We should add a migrate option to migrate the database upon pulling.

**Comment by iankronquist** [comment]
In my opinion, the Django resource should do collect_static and migrations. Maybe also debug.
- Managing packages is not Django specific.
- Database settings are settings and should be set the usual way to avoid duplicate work. Really what would we do, write to a template twice? I'm not even sure that makes sense.
- The sub-directory thing you had going on is weird, we're not doing that anymore, so we don't need to support it.

**Comment by iankronquist** [comment]
After talking with @tschuy we've decided we don't need a separate resource. We will add two new flags:
- django_migrate
- django_collectstatic

**Comment by justinnoah** [comment]
You _may_ want to add alembic_migrate as well. That is used in flask apps. Though the new workflow says no more flask, so maybe not.

**Comment by iankronquist** [comment]
@justinnoah I think we'll cross that bridge when we come to it, but thanks for saying so here for our future selves.
