### ISSUE TITLE
Flask Resource

### ISSUE THREAD

**Issue by justinnoah** [osuosl-cookbooks/python-webapp#9]
A flask resource is needed

Possible attributes:
- Debug
- Testing
- Configuration Location
  - Configuration Options

EDIT: Removed celery options (as discussed below, separate resource)

**Comment by iankronquist** [comment]
@brutal-chaos Would you mind writing up a list of attributes you see the Flask resource using?

**Comment by brutal-chaos** [comment]
@iankronquist yeah! was just working on that actually

**Comment by justinnoah** [comment]
I have added a few to start.

**Comment by iankronquist** [comment]
How are debug and testing different? How are configuration files typically handled in Flask (is there a typical way?) Right now I'm putting the configuration options and location in the [common resource](https://github.com/osuosl-cookbooks/python-webapp/blob/common_recipe/resources/common.rb) because the functionality is common between Django and Flask. Does that sound reasonable?
Should Celery go in a completely different resource?

**Comment by justinnoah** [comment]
Debugging is usually used for logging of debugging information and showing debug pages on your site if failure happens. Testing is usually set when running tests.

Configs are usually a config.py in the project directory. They however can be whatever (py, ini, yaml) and where ever though. It's left up to the application designer's preference.

I agree that celery should be in a separate resource.

**Comment by iankronquist** [comment]
@brutal-chaos What's the status on this?

**Comment by justinnoah** [comment]
@iankronquist I've not really touched on it just yet.

**Comment by tschuy** [comment]
How are debugging and testing set? Since configuration exists in the common cookbook, I feel like none of these are potentially necessary.

What about migrations?

**Comment by justinnoah** [comment]
Migrations are done outside of flask, for example, using another library like alembic. Migrations are really project specific and not flask specific.

**Comment by iankronquist** [comment]
I am in favor of closing this issue.
1. The new development workflow says we don't plan on writing any more flask apps
2. There are no notable features for a Flask resource which aren't covered by a common resource
3. @justinnoah probably won't be working on this.

**Comment by iankronquist** [comment]
After discussion with @tschuy we've decided this is not necessary.

**Comment by justinnoah** [comment]
I agree. I hadn't closed it myself just in case I discovered an actual reason for it.
